# Generated by Django 5.1.2 on 2024-10-30 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_vehiculo_consumo_promedio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='consumo_promedio',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='costos_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='distancia_promedio',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='frecuencia_conduccion',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='impuestos_vehiculares',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='kilometraje_anual',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='precio_combustible',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='seguros',
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('kilometraje_anual', models.PositiveIntegerField()),
                ('consumo_promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distancia_promedio', models.PositiveIntegerField()),
                ('frecuencia_conduccion', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=20)),
                ('precio_combustible', models.PositiveIntegerField()),
                ('costos_mantenimiento', models.PositiveIntegerField()),
                ('impuestos_vehiculares', models.PositiveIntegerField()),
                ('seguros', models.PositiveIntegerField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehiculo')),
            ],
        ),
    ]
