# Generated by Django 5.1.2 on 2024-11-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_vehiculo_consumo_promedio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='precio_combustible',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
