# Generated by Django 5.1.2 on 2024-11-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_consumo_precio_combustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='precio_combustible',
            field=models.PositiveIntegerField(),
        ),
    ]
