# Generated by Django 5.1.2 on 2024-11-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_consumo_precio_combustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='precio_combustible',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
